#!/usr/bin/env python3
"""ClawTalk PR Summary — generates prioritized merge guide"""

import json, sys, urllib.request
from datetime import datetime, timezone

REPO = "L0T-B0T/clawtalk"
fmt = sys.argv[1] if len(sys.argv) > 1 else "--markdown"

req = urllib.request.Request(
    f"https://api.github.com/repos/{REPO}/pulls?state=open&per_page=100",
    headers={"Accept": "application/vnd.github+json", "User-Agent": "Aaron/1.0"}
)
prs = json.loads(urllib.request.urlopen(req, timeout=15).read())

groups = {"docs": [], "client": [], "server": []}

for pr in prs:
    num = pr["number"]
    title = pr["title"]
    user = pr["user"]["login"]
    created = pr["created_at"][:10]
    t = title.lower()
    
    if any(w in t for w in ["docs", "readme", "api.md", "troubleshoot", "roadmap", "reference"]):
        group = "docs"
    elif any(w in t for w in ["server", "webhook auth", "endpoint"]):
        group = "server"
    else:
        group = "client"
    
    try:
        age = (datetime.now(timezone.utc) - datetime.fromisoformat(created + "T00:00:00+00:00")).days
    except:
        age = 0
    
    groups[group].append({"num": num, "title": title, "user": user, "created": created, "age": age})

if fmt == "--json":
    print(json.dumps({"total": len(prs), "groups": {k: len(v) for k,v in groups.items()}, "prs": groups}, indent=2))
else:
    print(f"# ClawTalk PR Merge Guide")
    print(f"**{len(prs)} PRs open, 0 merged** — generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print()
    
    priority = [
        ("docs", "📚 Documentation (ZERO RISK)", "No code changes. Pure documentation."),
        ("client", "🔧 Client Tools (LOW RISK)", "Self-contained tools. No server modifications."),
        ("server", "⚙️ Server Features (REVIEW NEEDED)", "Modify server behavior."),
    ]
    
    order = 1
    for key, header, desc in priority:
        items = sorted(groups[key], key=lambda x: x["num"])
        if not items:
            continue
        print(f"## {header}")
        print(f"*{desc}*\n")
        for item in items:
            print(f"{order}. **#{item['num']}** — {item['title']} (by {item['user']}, {item['age']}d)")
            order += 1
        print()
    
    print(f"---\n*Generated by ClawTalk PR Summary Tool (Aaron)*")

